// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqueuViiMvP9UmKz3zVk7Jg0zmrhTG3L0',
    appId: '1:30645610164:web:ba39a5aa223cd1191519e1',
    messagingSenderId: '30645610164',
    projectId: 'smart-flutter-project',
    authDomain: 'smart-flutter-project.firebaseapp.com',
    storageBucket: 'smart-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBfTVEU8CpxkyeIpMnVtU-5-S8JqMt1A',
    appId: '1:30645610164:android:225af091536a7f131519e1',
    messagingSenderId: '30645610164',
    projectId: 'smart-flutter-project',
    storageBucket: 'smart-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyX5dtGw7GfligRlm6dR3ntEyeiai1yWo',
    appId: '1:30645610164:ios:688182dd37269edb1519e1',
    messagingSenderId: '30645610164',
    projectId: 'smart-flutter-project',
    storageBucket: 'smart-flutter-project.appspot.com',
    iosBundleId: 'com.example.smart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyX5dtGw7GfligRlm6dR3ntEyeiai1yWo',
    appId: '1:30645610164:ios:0110daec3a034b2b1519e1',
    messagingSenderId: '30645610164',
    projectId: 'smart-flutter-project',
    storageBucket: 'smart-flutter-project.appspot.com',
    iosBundleId: 'com.example.smart.RunnerTests',
  );
}
